name: End-to-End Tests

on: [push]

jobs:
  test:
    name: Run TestCafe Tests
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm install

      - name: Run TestCafe Tests
        run: npm run test:e2e-gh
